/*
 * NON MODIFICARE A MANO. Generato da scripts/related-sites.mjs.
 *
 * Gruppi di siti che condividono lo stesso account, da
 * apple/password-manager-resources (licenza MIT, vedi NOTICE.md).
 *
 * A cosa serve qui: un alias creato su safeway.com vale anche su vons.com,
 * perche' e' un login solo. Senza questa tabella il popup aperto su vons.com
 * non trova niente e fa creare un secondo alias per lo stesso account.
 *
 * 298 domini in 53 gruppi simmetrici,
 * piu' 115 legami a senso unico.
 */
export const GROUPS = [
  ["3docean.net","audiojungle.net","codecanyon.net","envato.com","graphicriver.net","photodune.net","placeit.net","themeforest.net","tutsplus.com","videohive.net"],
  ["acmemarkets.com","albertsons.com","andronicos.com","balduccis.com","carrsqc.com","haggen.com","jewelosco.com","kingsfoodmarkets.com","pavilions.com","randalls.com","safeway.com","shaws.com","starmarket.com","tomthumb.com","vons.com"],
  ["airbnb.at","airbnb.be","airbnb.ca","airbnb.ch","airbnb.cl","airbnb.co.cr","airbnb.co.id","airbnb.co.in","airbnb.co.kr","airbnb.co.nz","airbnb.co.uk","airbnb.co.ve","airbnb.com","airbnb.com.ar","airbnb.com.au","airbnb.com.bo","airbnb.com.br","airbnb.com.bz","airbnb.com.co","airbnb.com.ec","airbnb.com.gt","airbnb.com.hk","airbnb.com.hn","airbnb.com.mt","airbnb.com.my","airbnb.com.ni","airbnb.com.pa","airbnb.com.pe","airbnb.com.py","airbnb.com.sg","airbnb.com.sv","airbnb.com.tr","airbnb.com.tw","airbnb.cz","airbnb.de","airbnb.dk","airbnb.es","airbnb.fi","airbnb.fr","airbnb.gr","airbnb.gy","airbnb.hu","airbnb.ie","airbnb.is","airbnb.it","airbnb.jp","airbnb.mx","airbnb.nl","airbnb.no","airbnb.pl","airbnb.pt","airbnb.ru","airbnb.se"],
  ["airfrance.com","airfranceklm.com","flyingblue.com","klm.com"],
  ["airnewzealand.co.nz","airnewzealand.com","airnewzealand.com.au"],
  ["albertsonsmarket.com","amigosunited.com","marketstreetunited.com","unitedsupermarkets.com"],
  ["alelo.com.br","meualelo.com.br"],
  ["alibaba.com","aliexpress.com","aliexpress.us"],
  ["ana.co.jp","astyle.jp"],
  ["anthem.com","sydneyhealth.com"],
  ["app.onsign.com","app.onsign.tv"],
  ["bgg.cc","boardgamegeek.com","rpggeek.com","videogamegeek.com"],
  ["bsky.app","bsky.social"],
  ["candyrect.com","nekochat.cn"],
  ["casemates.com","hammacher.com","mediocre.com","mediocre.org","meh.com","mercatalyst.com","morningsave.com","shop.univision.com","sidedeal.com","stores.com"],
  ["centralfcu.com","centralfcu.org"],
  ["chat.com","chatgpt.com","openai.com"],
  ["check24.at","check24.com","check24.de","check24.es"],
  ["collecting.com","collectingcars.com","watchcollecting.com"],
  ["coolblue.be","coolblue.de","coolblue.nl"],
  ["dan.org","diversalertnetwork.org"],
  ["discord.store","discordmerch.com"],
  ["disney.com","disneyplus.com","disneystore.com","espn.com","go.com","hulu.com","shopdisney.com"],
  ["dnt.abine.com","ironvest.com"],
  ["dmsguild.com","drivethrucards.com","drivethrucomics.com","drivethrufiction.com","drivethrurpg.com","pathfinderinfinite.com","storytellersvault.com","wargamevault.com"],
  ["e621.net","e926.net"],
  ["ebay.at","ebay.be","ebay.ca","ebay.ch","ebay.cn","ebay.co.th","ebay.co.uk","ebay.com","ebay.com.au","ebay.com.hk","ebay.com.my","ebay.com.sg","ebay.com.tw","ebay.de","ebay.es","ebay.fr","ebay.ie","ebay.it","ebay.nl","ebay.ph","ebay.pl","ebay.vn"],
  ["epicgames.com","fortnite.com","twinmotion.com","unrealengine.com"],
  ["eventbrite.at","eventbrite.be","eventbrite.ca","eventbrite.ch","eventbrite.cl","eventbrite.co","eventbrite.com","eventbrite.de","eventbrite.dk","eventbrite.es","eventbrite.fi","eventbrite.fr","eventbrite.hk","eventbrite.ie","eventbrite.in","eventbrite.it","eventbrite.my","eventbrite.nl","eventbrite.ph","eventbrite.pt","eventbrite.se","eventbrite.sg"],
  ["hejj.io","skoophr.com"],
  ["instagram.com","threads.com","threads.net"],
  ["koboldpress.com","labyrinth.talesofthevaliant.com"],
  ["lrz.de","mwn.de","mytum.de","tum.de","tum.edu"],
  ["melio.com","meliopayments.com"],
  ["monarch.com","monarchmoney.com"],
  ["padmapper.com","zumper.com","zumperrentals.com"],
  ["pinterest.at","pinterest.ca","pinterest.ch","pinterest.cl","pinterest.co.kr","pinterest.co.uk","pinterest.com","pinterest.com.au","pinterest.com.mx","pinterest.de","pinterest.dk","pinterest.es","pinterest.fr","pinterest.ie","pinterest.it","pinterest.jp","pinterest.nz","pinterest.ph","pinterest.pt","pinterest.ru","pinterest.se"],
  ["playstation.com","sony.com","sonyentertainmentnetwork.com"],
  ["portal.fitnesspassport.app","portal.fitnesspassport.co.nz","portal.fitnesspassport.com.au"],
  ["postnl.be","postnl.nl"],
  ["pretendo.cc","pretendo.network"],
  ["proton.me","protonmail.ch","protonmail.com","protonvpn.com"],
  ["prtimes.com","prtimes.jp"],
  ["quicken.com","simplifimoney.com"],
  ["redis.com","redislabs.com"],
  ["community.pioneerdj.com","pioneerdj.com","rekordbox.com"],
  ["rentcafe.com","securecafe.com"],
  ["profile.callofduty.com","s.activision.com"],
  ["steamcommunity.com","steamgames.com","steampowered.com"],
  ["express1040.com","freetaxusa.com","taxhawk.com"],
  ["ting.com","tingmobile.com"],
  ["uspowerboating.com","ussailing.org"],
  ["auth.wikimedia.org","commons.wikimedia.org","incubator.wikimedia.org","mediawiki.org","meta.wikimedia.org","outreach.wikimedia.org","species.wikimedia.org","wikibooks.org","wikidata.org","wikimania.wikimedia.org","wikinews.org","wikipedia.org","wikiquote.org","wikisource.org","wikiversity.org","wikivoyage.org","wiktionary.org"],
]

export const INDEX = {
  '3docean.net': 0,
  'acmemarkets.com': 1,
  'airbnb.at': 2,
  'airbnb.be': 2,
  'airbnb.ca': 2,
  'airbnb.ch': 2,
  'airbnb.cl': 2,
  'airbnb.co.cr': 2,
  'airbnb.co.id': 2,
  'airbnb.co.in': 2,
  'airbnb.co.kr': 2,
  'airbnb.co.nz': 2,
  'airbnb.co.uk': 2,
  'airbnb.co.ve': 2,
  'airbnb.com': 2,
  'airbnb.com.ar': 2,
  'airbnb.com.au': 2,
  'airbnb.com.bo': 2,
  'airbnb.com.br': 2,
  'airbnb.com.bz': 2,
  'airbnb.com.co': 2,
  'airbnb.com.ec': 2,
  'airbnb.com.gt': 2,
  'airbnb.com.hk': 2,
  'airbnb.com.hn': 2,
  'airbnb.com.mt': 2,
  'airbnb.com.my': 2,
  'airbnb.com.ni': 2,
  'airbnb.com.pa': 2,
  'airbnb.com.pe': 2,
  'airbnb.com.py': 2,
  'airbnb.com.sg': 2,
  'airbnb.com.sv': 2,
  'airbnb.com.tr': 2,
  'airbnb.com.tw': 2,
  'airbnb.cz': 2,
  'airbnb.de': 2,
  'airbnb.dk': 2,
  'airbnb.es': 2,
  'airbnb.fi': 2,
  'airbnb.fr': 2,
  'airbnb.gr': 2,
  'airbnb.gy': 2,
  'airbnb.hu': 2,
  'airbnb.ie': 2,
  'airbnb.is': 2,
  'airbnb.it': 2,
  'airbnb.jp': 2,
  'airbnb.mx': 2,
  'airbnb.nl': 2,
  'airbnb.no': 2,
  'airbnb.pl': 2,
  'airbnb.pt': 2,
  'airbnb.ru': 2,
  'airbnb.se': 2,
  'airfrance.com': 3,
  'airfranceklm.com': 3,
  'airnewzealand.co.nz': 4,
  'airnewzealand.com': 4,
  'airnewzealand.com.au': 4,
  'albertsons.com': 1,
  'albertsonsmarket.com': 5,
  'alelo.com.br': 6,
  'alibaba.com': 7,
  'aliexpress.com': 7,
  'aliexpress.us': 7,
  'amigosunited.com': 5,
  'ana.co.jp': 8,
  'andronicos.com': 1,
  'anthem.com': 9,
  'app.onsign.com': 10,
  'app.onsign.tv': 10,
  'astyle.jp': 8,
  'audiojungle.net': 0,
  'auth.wikimedia.org': 52,
  'balduccis.com': 1,
  'bgg.cc': 11,
  'boardgamegeek.com': 11,
  'bsky.app': 12,
  'bsky.social': 12,
  'candyrect.com': 13,
  'carrsqc.com': 1,
  'casemates.com': 14,
  'centralfcu.com': 15,
  'centralfcu.org': 15,
  'chat.com': 16,
  'chatgpt.com': 16,
  'check24.at': 17,
  'check24.com': 17,
  'check24.de': 17,
  'check24.es': 17,
  'codecanyon.net': 0,
  'collecting.com': 18,
  'collectingcars.com': 18,
  'commons.wikimedia.org': 52,
  'community.pioneerdj.com': 45,
  'coolblue.be': 19,
  'coolblue.de': 19,
  'coolblue.nl': 19,
  'dan.org': 20,
  'discord.store': 21,
  'discordmerch.com': 21,
  'disney.com': 22,
  'disneyplus.com': 22,
  'disneystore.com': 22,
  'diversalertnetwork.org': 20,
  'dmsguild.com': 24,
  'dnt.abine.com': 23,
  'drivethrucards.com': 24,
  'drivethrucomics.com': 24,
  'drivethrufiction.com': 24,
  'drivethrurpg.com': 24,
  'e621.net': 25,
  'e926.net': 25,
  'ebay.at': 26,
  'ebay.be': 26,
  'ebay.ca': 26,
  'ebay.ch': 26,
  'ebay.cn': 26,
  'ebay.co.th': 26,
  'ebay.co.uk': 26,
  'ebay.com': 26,
  'ebay.com.au': 26,
  'ebay.com.hk': 26,
  'ebay.com.my': 26,
  'ebay.com.sg': 26,
  'ebay.com.tw': 26,
  'ebay.de': 26,
  'ebay.es': 26,
  'ebay.fr': 26,
  'ebay.ie': 26,
  'ebay.it': 26,
  'ebay.nl': 26,
  'ebay.ph': 26,
  'ebay.pl': 26,
  'ebay.vn': 26,
  'envato.com': 0,
  'epicgames.com': 27,
  'espn.com': 22,
  'eventbrite.at': 28,
  'eventbrite.be': 28,
  'eventbrite.ca': 28,
  'eventbrite.ch': 28,
  'eventbrite.cl': 28,
  'eventbrite.co': 28,
  'eventbrite.com': 28,
  'eventbrite.de': 28,
  'eventbrite.dk': 28,
  'eventbrite.es': 28,
  'eventbrite.fi': 28,
  'eventbrite.fr': 28,
  'eventbrite.hk': 28,
  'eventbrite.ie': 28,
  'eventbrite.in': 28,
  'eventbrite.it': 28,
  'eventbrite.my': 28,
  'eventbrite.nl': 28,
  'eventbrite.ph': 28,
  'eventbrite.pt': 28,
  'eventbrite.se': 28,
  'eventbrite.sg': 28,
  'express1040.com': 49,
  'flyingblue.com': 3,
  'fortnite.com': 27,
  'freetaxusa.com': 49,
  'go.com': 22,
  'graphicriver.net': 0,
  'haggen.com': 1,
  'hammacher.com': 14,
  'hejj.io': 29,
  'hulu.com': 22,
  'incubator.wikimedia.org': 52,
  'instagram.com': 30,
  'ironvest.com': 23,
  'jewelosco.com': 1,
  'kingsfoodmarkets.com': 1,
  'klm.com': 3,
  'koboldpress.com': 31,
  'labyrinth.talesofthevaliant.com': 31,
  'lrz.de': 32,
  'marketstreetunited.com': 5,
  'mediawiki.org': 52,
  'mediocre.com': 14,
  'mediocre.org': 14,
  'meh.com': 14,
  'melio.com': 33,
  'meliopayments.com': 33,
  'mercatalyst.com': 14,
  'meta.wikimedia.org': 52,
  'meualelo.com.br': 6,
  'monarch.com': 34,
  'monarchmoney.com': 34,
  'morningsave.com': 14,
  'mwn.de': 32,
  'mytum.de': 32,
  'nekochat.cn': 13,
  'openai.com': 16,
  'outreach.wikimedia.org': 52,
  'padmapper.com': 35,
  'pathfinderinfinite.com': 24,
  'pavilions.com': 1,
  'photodune.net': 0,
  'pinterest.at': 36,
  'pinterest.ca': 36,
  'pinterest.ch': 36,
  'pinterest.cl': 36,
  'pinterest.co.kr': 36,
  'pinterest.co.uk': 36,
  'pinterest.com': 36,
  'pinterest.com.au': 36,
  'pinterest.com.mx': 36,
  'pinterest.de': 36,
  'pinterest.dk': 36,
  'pinterest.es': 36,
  'pinterest.fr': 36,
  'pinterest.ie': 36,
  'pinterest.it': 36,
  'pinterest.jp': 36,
  'pinterest.nz': 36,
  'pinterest.ph': 36,
  'pinterest.pt': 36,
  'pinterest.ru': 36,
  'pinterest.se': 36,
  'pioneerdj.com': 45,
  'placeit.net': 0,
  'playstation.com': 37,
  'portal.fitnesspassport.app': 38,
  'portal.fitnesspassport.co.nz': 38,
  'portal.fitnesspassport.com.au': 38,
  'postnl.be': 39,
  'postnl.nl': 39,
  'pretendo.cc': 40,
  'pretendo.network': 40,
  'profile.callofduty.com': 47,
  'proton.me': 41,
  'protonmail.ch': 41,
  'protonmail.com': 41,
  'protonvpn.com': 41,
  'prtimes.com': 42,
  'prtimes.jp': 42,
  'quicken.com': 43,
  'randalls.com': 1,
  'redis.com': 44,
  'redislabs.com': 44,
  'rekordbox.com': 45,
  'rentcafe.com': 46,
  'rpggeek.com': 11,
  's.activision.com': 47,
  'safeway.com': 1,
  'securecafe.com': 46,
  'shaws.com': 1,
  'shop.univision.com': 14,
  'shopdisney.com': 22,
  'sidedeal.com': 14,
  'simplifimoney.com': 43,
  'skoophr.com': 29,
  'sony.com': 37,
  'sonyentertainmentnetwork.com': 37,
  'species.wikimedia.org': 52,
  'starmarket.com': 1,
  'steamcommunity.com': 48,
  'steamgames.com': 48,
  'steampowered.com': 48,
  'stores.com': 14,
  'storytellersvault.com': 24,
  'sydneyhealth.com': 9,
  'taxhawk.com': 49,
  'themeforest.net': 0,
  'threads.com': 30,
  'threads.net': 30,
  'ting.com': 50,
  'tingmobile.com': 50,
  'tomthumb.com': 1,
  'tum.de': 32,
  'tum.edu': 32,
  'tutsplus.com': 0,
  'twinmotion.com': 27,
  'unitedsupermarkets.com': 5,
  'unrealengine.com': 27,
  'uspowerboating.com': 51,
  'ussailing.org': 51,
  'videogamegeek.com': 11,
  'videohive.net': 0,
  'vons.com': 1,
  'wargamevault.com': 24,
  'watchcollecting.com': 18,
  'wikibooks.org': 52,
  'wikidata.org': 52,
  'wikimania.wikimedia.org': 52,
  'wikinews.org': 52,
  'wikipedia.org': 52,
  'wikiquote.org': 52,
  'wikisource.org': 52,
  'wikiversity.org': 52,
  'wikivoyage.org': 52,
  'wiktionary.org': 52,
  'zumper.com': 35,
  'zumperrentals.com': 35,
}

export const DIRECTED = {
  'a2hosting.com': ["hosting.com"],
  'adobelogin.com': ["adobe.com"],
  'angel.co': ["wellfound.com"],
  'appannie.com': ["data.ai"],
  'behance.net': ["adobe.com"],
  'bit.ly': ["bitly.com"],
  'carsensor.net': ["point.recruit.co.jp"],
  'cleanshot.cloud': ["cleanshot.com"],
  'costco.ca': ["signin.costco.com"],
  'dhl.com': ["mydhl.express.dhl"],
  'digiromania.ro': ["digi.ro"],
  'discordapp.com': ["discord.com"],
  'discovercard.com': ["discover.com"],
  'dq.com': ["dairyqueen.com"],
  'eo.nl': ["id.npo.nl"],
  'fancourier.ro': ["selfawb.ro"],
  'flaglerclerk.com': ["flaglerclerk.gov"],
  'flyblade.com': ["blade.com"],
  'gamefaqs.com': ["gamefaqs.gamespot.com"],
  'gamepedia.com': ["fandom.com"],
  'gazduire.com.ro': ["admin.ro"],
  'gazduire.net': ["admin.ro"],
  'gld.nl': ["id.npo.nl"],
  'hawaiianairlines.com': ["alaskaair.com"],
  'hbo.com': ["max.com"],
  'hbomax.com': ["max.com"],
  'hbonow.com': ["max.com"],
  'hdfcbank.com': ["hdfc.bank.in"],
  'heroku.com': ["verify.salesforce.com"],
  'hk.jobsdb.com': ["login.seek.com"],
  'ing.de': ["ing.com"],
  'jobsdb.com': ["login.seek.com"],
  'jobstreet.com': ["login.seek.com"],
  'kakao.com': ["daum.net"],
  'keypointcu.com': ["kpcu.com"],
  'kro-ncrv.nl': ["id.npo.nl"],
  'l1.nl': ["id.npo.nl"],
  'lendingclub.com': ["happen.com"],
  'letsdeel.com': ["deel.com"],
  'login.workflowmanager.app': ["infotechexpress.com"],
  'mercadolibre.cl': ["mercadolibre.com"],
  'mercadolibre.co.cr': ["mercadolibre.com"],
  'mercadolibre.com.ar': ["mercadolibre.com"],
  'mercadolibre.com.bo': ["mercadolibre.com"],
  'mercadolibre.com.co': ["mercadolibre.com"],
  'mercadolibre.com.do': ["mercadolibre.com"],
  'mercadolibre.com.ec': ["mercadolibre.com"],
  'mercadolibre.com.gt': ["mercadolibre.com"],
  'mercadolibre.com.hn': ["mercadolibre.com"],
  'mercadolibre.com.mx': ["mercadolibre.com"],
  'mercadolibre.com.ni': ["mercadolibre.com"],
  'mercadolibre.com.pa': ["mercadolibre.com"],
  'mercadolibre.com.pe': ["mercadolibre.com"],
  'mercadolibre.com.py': ["mercadolibre.com"],
  'mercadolibre.com.sv': ["mercadolibre.com"],
  'mercadolibre.com.uy': ["mercadolibre.com"],
  'mercadolibre.com.ve': ["mercadolibre.com"],
  'mercadolivre.com.br': ["mercadolivre.com"],
  'mercadopago.cl': ["mercadolibre.com"],
  'mercadopago.com.ar': ["mercadolibre.com"],
  'mercadopago.com.br': ["mercadolivre.com"],
  'mercadopago.com.co': ["mercadolibre.com"],
  'mercadopago.com.ec': ["mercadolibre.com"],
  'mercadopago.com.mx': ["mercadolibre.com"],
  'mercadopago.com.pe': ["mercadolibre.com"],
  'mercadopago.com.uy': ["mercadolibre.com"],
  'mercadopago.com.ve': ["mercadolibre.com"],
  'moneybird.de': ["moneybird.com"],
  'moneybird.nl': ["moneybird.com"],
  'myjobstreet.jobstreet.co.id': ["login.seek.com"],
  'myjobstreet.jobstreet.com.my': ["login.seek.com"],
  'myjobstreet.jobstreet.com.ph': ["login.seek.com"],
  'myjobstreet.jobstreet.com.sg': ["login.seek.com"],
  'nebula.app': ["nebula.tv"],
  'nextinpact.com': ["next.ink"],
  'nordpass.com': ["nordaccount.com"],
  'nordvpn.com': ["nordaccount.com"],
  'npo.nl': ["id.npo.nl"],
  'npoluister.nl': ["id.npo.nl"],
  'nporadio5.nl': ["id.npo.nl"],
  'omroepwest.nl': ["id.npo.nl"],
  'omroepzeeland.nl': ["id.npo.nl"],
  'omropfryslan.nl': ["id.npo.nl"],
  'oost.nl': ["id.npo.nl"],
  'overstock.com': ["bedbathandbeyond.com"],
  'parkmobile.us': ["parkmobile.io"],
  'peacock.com': ["peacocktv.com"],
  'raywenderlich.com': ["kodeco.com"],
  'rcs-rds.ro': ["digi.ro"],
  'rijnmond.nl': ["id.npo.nl"],
  'rtvdrenthe.nl': ["id.npo.nl"],
  'rtvnoord.nl': ["id.npo.nl"],
  'rtvutrecht.nl': ["id.npo.nl"],
  'scottscheapflights.com': ["going.com"],
  'sg.jobsdb.com': ["login.seek.com"],
  'sncf-connect.com': ["auth.monidentifiant.sncf"],
  'telegram.me': ["telegram.org"],
  'th.jobsdb.com': ["login.seek.com"],
  'transferwise.com': ["wise.com"],
  'tvnow.at': ["auth.rtl.de","rtlplus.com","rtlplus.de"],
  'tvnow.ch': ["auth.rtl.de","rtlplus.com","rtlplus.de"],
  'tvnow.de': ["auth.rtl.de","rtlplus.com","rtlplus.de"],
  'twitter.com': ["x.com"],
  'wacom.eu': ["wacom.com"],
  'watchnebula.com': ["nebula.tv"],
  'wikia.com': ["fandom.com"],
  'wikia.org': ["fandom.com"],
  'wikicities.com': ["fandom.com"],
  'wnl.tv': ["id.npo.nl"],
  'workflowmanager.app': ["infotechexpress.com"],
  'www.seek.co.nz': ["login.seek.com"],
  'www.seek.com.au': ["login.seek.com"],
  'www.vistaprint.ca': ["account.vistaprint.com"],
  'xiaomi.com': ["mi.com"],
  'youneedabudget.com': ["ynab.com"],
}

/**
 * Gli altri domini che condividono l'account con questo. Mai se stesso.
 *
 * Chi la usa deve dire da dove viene l'alias che mostra: suggerire una cosa
 * salvata per un dominio diverso senza dirlo e' il modo in cui un elenco di
 * comodo diventa una trappola. Vale anche per noi, non solo per le password.
 */
export function relatedSites(domain) {
  if (typeof domain !== 'string') return []

  const key = domain.toLowerCase()
  const group = INDEX[key] === undefined ? [] : GROUPS[INDEX[key]]

  return [...new Set([...group, ...(DIRECTED[key] ?? [])])].filter((d) => d !== key)
}

/*
 * Servizi che, dentro un riquadro su un altro sito, chiedono le credenziali
 * di un servizio terzo. Da apple/password-manager-resources
 * (quirks/websites-that-ask-for-credentials-for-other-services-when-embedded-as-third-party.json,
 * licenza MIT, vedi NOTICE.md).
 *
 * Cosa c'entra con noi. Il nostro script gira in tutti i riquadri e legge il
 * nome dell'host del riquadro, non della pagina. Nel riquadro di Plaid dentro
 * il sito di una banca finivamo quindi per proporre un alias e registrarlo su
 * plaid.com, mentre l'account e' della banca: un indirizzo attribuito a un
 * posto in cui non verra' mai usato. Qui non offriamo e non registriamo
 * niente: in questi riquadri si stanno collegando conti correnti, e un
 * suggerimento nostro sarebbe fuori posto anche a prescindere dall'etichetta
 * sbagliata.
 */
export const THIRD_PARTY_CREDENTIAL_FRAMES = new Set(["aeropay.com","aerosync.com","plaid.com","schwab.com"])

/** Siamo dentro il riquadro di un servizio che chiede credenziali altrui? */
export function isThirdPartyCredentialFrame(domain, inFrame) {
  if (!inFrame || typeof domain !== 'string') return false

  return THIRD_PARTY_CREDENTIAL_FRAMES.has(domain.toLowerCase())
}
